name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag msosav/toysnt:latest
      
    - name: Docker Push
      run: docker push msosav/toysnt
